<?php
/** @var \Application\UsersPhones\Row $row */

use Application\UsersPhones\Table;

$uid = uniqid('form_', false);
$url = $this->url('phones', 'crud');
?>
<form id="<?=$uid?>" action="<?=$url?>" class="form-horizontal" data-ajax method="POST">
  <input type="hidden" name="_method" value="<?=$method?>"/>
  <div class="modal-header">
    <h4 class="modal-title"><?=__('UsersPhones')?></h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <input type="hidden" id="id" name="id" value="<?= $row['id'] ?>"/>
    <div class="form-group row">
      <label class="col-form-label col-lg-4" for="userId"><?=__('userId')?></label>
      <div class="col-lg-8">
        <input type="number" id="userId" name="userId" class="form-control" value="<?= $row['userId'] ?>"/>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-form-label col-lg-4" for="number"><?=__('number')?></label>
      <div class="col-lg-8">
        <input type="text" id="number" name="number" class="form-control" value="<?= $row['number'] ?>"/>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-form-label col-lg-4" for="status"><?=__('status')?></label>
      <div class="col-lg-8">
        <?= $this->select('status', [
            Table::STATUS_PENDING => __(Table::STATUS_PENDING),
            Table::STATUS_ACTIVE => __(Table::STATUS_ACTIVE),
            Table::STATUS_DISABLED => __(Table::STATUS_DISABLED),
            Table::STATUS_DELETED => __(Table::STATUS_DELETED)
        ], $row['status'], ['id' => 'status', 'class' => 'form-control']);?>
      </div>
    </div>
    <!-- Place additional form fields here -->
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Save</button>
    <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
  </div>
</form>
<?php
// need for plain request
if (isset($errors)) :
    $this->partial('crud/errors.phtml', ['uid' => $uid, 'errors' => $errors]);
endif;
?>