<?php
/**
 * @var \Bluz\Grid\Grid $grid
 */

use Application\UsersPhones\Table;

if (!$grid) return;
$uid = $grid->getUid();
?>
<div class="clearfix" data-spy="grid" data-grid="<?=$uid?>">
  <script>
    // use data-spy="grid" for use AJAX for reload grid
    require(['bluz.grid']);
  </script>

  <nav class="navbar navbar-light bg-light justify-content-between">
    <div>
      <a href="<?=$this->url('phones', 'crud')?>" class="btn btn-primary"
         data-ajax-dialog data-ajax-method="get" data-modal-style="modal-lg">
         <?= __('Create') ?>      </a>
      <!-- Place filters here -->
      <a href="<?= $grid->filter('status', 'eq', false, true) ?>" data-ajax
         class="btn btn-secondary <?= (!$grid->getFilter('status', 'eq') ? 'btn-info' : '') ?>">
          <?= __('All') ?>
      </a>
      <a href="<?= $grid->filter('status', 'eq', Table::STATUS_PENDING) ?>" data-ajax
         class="btn btn-secondary <?= (Table::STATUS_PENDING === $grid->getFilter('status', 'eq')? 'btn-info' : '') ?>">
          <?= Table::STATUS_PENDING ?>
      </a>
      <a href="<?= $grid->filter('status', 'eq', Table::STATUS_ACTIVE) ?>" data-ajax
         class="btn btn-secondary <?= (Table::STATUS_ACTIVE === $grid->getFilter('status', 'eq')? 'btn-info' : '') ?>">
          <?= Table::STATUS_ACTIVE ?>
      </a>
      <a href="<?= $grid->filter('status', 'eq', Table::STATUS_DISABLED) ?>" data-ajax
         class="btn btn-secondary <?= (Table::STATUS_DISABLED === $grid->getFilter('status', 'eq')? 'btn-info' : '') ?>">
          <?= Table::STATUS_DISABLED ?>
      </a>
      <a href="<?= $grid->filter('status', 'eq', Table::STATUS_DELETED) ?>" data-ajax
         class="btn btn-secondary <?= (Table::STATUS_DELETED === $grid->getFilter('status', 'eq')? 'btn-info' : '') ?>">
          <?= Table::STATUS_DELETED ?>
      </a>
    </div>
    <!-- Place search form here -->
    <form action="<?= $this->url('phones', 'grid') ?>" class="form-inline filter-form">
      <div class="input-group">
          <?php echo
          $this->partial(
              'grid/filter-search-advanced.phtml',
              [
                  'grid' => $grid,
                  'filters' => [
                      __('Phone') => [$grid::FILTER_LIKE => 'number'],
                  ]
              ]
          )
          ?>
        <span class="input-group-btn">
          <button class="btn btn-secondary"><?= __('Search') ?></button>
        </span>
      </div>
    </form>
  </nav>

  <hr/>

  <?=$this->partial('grid/total.phtml', ['grid'=>$grid]) ?>
  <?=$this->partial('grid/limit.phtml', ['grid'=>$grid]) ?>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th><a href="<?= $grid->order('id') ?: '#' ?>"><?= __('Id') ?></a></th>
        <th><a href="<?= $grid->order('userId') ?: '#' ?>"><?= __('UserId') ?></a></th>
        <th><a href="<?= $grid->order('number') ?: '#' ?>"><?= __('Phone') ?></a></th>
        <th><a href="<?= $grid->order('status') ?: '#' ?>"><?= __('Status') ?></a></th>
        <th><a href="<?= $grid->order('created') ?: '#' ?>"><?= __('Created') ?></a></th>
        <th><a href="<?= $grid->order('updated') ?: '#' ?>"><?= __('Updated') ?></a></th>
        <!-- Place your column headers here, for generate link for order use method $grid->order('column name') -->
        <th width="160px"></th>
      </tr>
    </thead>
    <tbody>
      <?php foreach($grid->getData() as $row) : ?>
      <tr>
        <td><?= $row['id'] ?></td>
        <td><a href="<?=$this->url('users', 'profile', ['id' => $row['userId']])?>"
               data-ajax-dialog data-ajax-method="get" data-modal-style="modal-lg"><?= $row->getUser()->login ?></a></td>
        <td><?= $row['number'] ?></td>
        <td><?= $row['status'] ?></td>
        <td><?= $row['created'] ?></td>
        <td><?= $row['updated'] ?></td>
        <!-- Place your content her, use $row['column name'] -->
        <td class="controls">
          <a href="<?= $this->url('phones', 'crud', ['id' => $row['id']]) ?>" class="btn btn-primary"
             data-ajax-dialog data-ajax-method="get" data-modal-style="modal-lg">
            <i class="fa fa-pencil"></i>
          </a>
          <a href="<?= $this->url('phones', 'crud', ['id' => $row['id']]) ?>" class="btn btn-danger"
             data-confirm data-ajax data-ajax-method="delete">
            <i class="fa fa-trash-o"></i>
          </a>
        </td>
      </tr>
      <?php endforeach; ?>
    </tbody>
  </table>

  <?=$this->partial('grid/empty-rows.phtml', ['grid'=>$grid]) ?>
  <?=$this->partial('grid/pagination.phtml', ['grid'=>$grid]) ?>
  <?=$this->partial('grid/total.phtml', ['grid'=>$grid]) ?>

</div>
